// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHIAs4EQNB-spFsFU19-0Ssw06Cay4lBs',
    appId: '1:796895517287:web:d1dd1b5a6cece67b14d2c2',
    messagingSenderId: '796895517287',
    projectId: 'coworking-53933',
    authDomain: 'coworking-53933.firebaseapp.com',
    storageBucket: 'coworking-53933.appspot.com',
    measurementId: 'G-GLDQPSNL50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJi3nkXHO0KfkK_JDFl9OA0JmkcwEXzC0',
    appId: '1:796895517287:android:d8959f3bdfbbe80614d2c2',
    messagingSenderId: '796895517287',
    projectId: 'coworking-53933',
    storageBucket: 'coworking-53933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAhBj1InrMqxyJf3SmGYpiBki-WZCuwCw',
    appId: '1:796895517287:ios:a3bf5f65c1894d3514d2c2',
    messagingSenderId: '796895517287',
    projectId: 'coworking-53933',
    storageBucket: 'coworking-53933.appspot.com',
    iosBundleId: 'com.example.coworkingApp',
  );
}
